benchmark:
  name: "Iris_Clustering_Benchmark"
  dataset: "data/iris.csv"  # Famous Iris dataset with 3 natural clusters

pipeline_template:
  - type: "clustering"
    algorithms: ["Hierarchical", "DBSCAN"]
    params:
      Hierarchical:
        n_clusters: 3
        linkage: "complete"
        distance_measure: "Cosine"
      DBSCAN:
        eps: 0.6
        min_samples: 4
        distance_measure: "Manhattan"
        # Optimized parameters for Iris dataset (150 samples)

  - type: "clustering_quality"
    algorithms: ["Calinski_Harabasz", "Davies_Bouldin"]
    params:
      Calinski_Harabasz: {}  # Default parameters
      Davies_Bouldin: {}     # Default parameters

# Distance measure configuration (Manhattan distance for comparison)
distance_measure: "Manhattan"

# Benchmark execution settings
iterations: 3  # Run each combination 3 times for statistical reliability

# Output configuration
output:
  directory: "benchmark_results"
  format: ["csv"]  

# Additional benchmark settings
timeout: 300  # 5 minutes timeout per benchmark run
verbose: true  # Enable detailed logging