benchmark:
  name: "DR_Clustering_Quality_Benchmark"
  dataset: "data/iris.csv"

pipeline_template:
  - type: "dimensionality_reduction"
    algorithms: ["PCA", "MDS", "TSNE"]
    params:
      PCA:
        n_components: 2
      MDS:
        n_components: 2
        max_iter: 300
        distance_measure: "Euclidean"
      TSNE:
        n_components: 2
        perplexity: 30
        max_iter: 1000
        distance_measure: "Euclidean"

  - type: "clustering"
    algorithms: ["Hierarchical", "DBSCAN", "KMeans"]
    params:
      Hierarchical:
        n_clusters: 3
        linkage: "complete"
        distance_measure: "Euclidean"
      DBSCAN:
        eps: 0.6
        min_samples: 4
        distance_measure: "Euclidean"
      KMeans:
        n_clusters: 3
        max_iter: 300
        random_state: 42

  - type: "clustering_quality"
    algorithms: ["Calinski_Harabasz", "Davies_Bouldin", "Silhouette"]
    params:
      Calinski_Harabasz: {}
      Davies_Bouldin: {}
      Silhouette: {}

# Benchmark execution settings
iterations: 3

# Output configuration
output:
  directory: "benchmark_results"
  format: ["csv"]

# Additional benchmark settings
timeout: 300
verbose: true